stages:
  - compile
  - static
  - build
  - deploy
  - trigger
compile:
  stage: compile
  image:
    name: librespace/kaitai
    entrypoint: [""]
  script:
    - /usr/bin/ksc --target python --outdir satnogsdecoders/decoder ksy/*.ksy
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - satnogsdecoders/decoder
static:
  stage: static
  image: python:2.7
  before_script:
    - pip install tox
  script:
    - tox -e yamllint,flake8,yapf,pylint
build:
  stage: build
  image: python:2.7
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
build3:
  stage: build
  image: python:3.6
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
deploy:
  stage: deploy
  image: python:2.7
  before_script:
    - pip install twine
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
    - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    refs:
      - tags
    variables:
      - $PYPI_USERNAME
      - $PYPI_PASSWORD
trigger:
  stage: trigger
  image: alpine
  before_script:
    - apk add --no-cache curl git
  script:
    # XXX: Workaround for GitLab missing latest tag pipeline triggering feature
    - |
      SATNOGS_DB_LATEST="${SATNOGS_DB_GIT_URL:+$(git ls-remote -q --tags --refs --exit-code --sort="v:refname" "$SATNOGS_DB_GIT_URL" | awk 'BEGIN { FS="/" } END { print $3 }')}"
      PIPELINE_TRIGGERS=$(echo "$PIPELINE_TRIGGERS" | sed 's/${SATNOGS_DB_LATEST}/'"$SATNOGS_DB_LATEST"'/g')
    - for trigger in $PIPELINE_TRIGGERS; do curl -X POST "$trigger"; done
  only:
    refs:
      - tags
    variables:
      - $PIPELINE_TRIGGERS
