stages:
  - compile
  - static
  - build
  - test
  - deploy
  - trigger
compile:
  stage: compile
  image:
    name: librespace/kaitai
    entrypoint: [""]
  script:
    - /usr/bin/ksc --target python --outdir satnogsdecoders/decoder ksy/*.ksy
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - satnogsdecoders/decoder
static_python:
  stage: static
  image: python:2
  before_script:
    - pip install tox~=3.8.0
  script:
    - tox -e "yamllint,py2-flake8,yapf,py2-pylint"
static_python3:
  stage: static
  image: python:3
  before_script:
    - pip install tox~=3.8.0
  script:
    - tox -e "py3-flake8,py3-pylint"
build:
  stage: build
  image: python:2
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
build3:
  stage: build
  image: python:3
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
test:
  stage: test
  image: python:2
  before_script:
    - pip install tox~=3.8.0
  script:
    - tox -e "py2-pytest"
test3:
  stage: test
  image: python:3
  before_script:
    - pip install tox~=3.8.0
  script:
    - tox -e "py3-pytest"
deploy:
  stage: deploy
  image: python:2
  before_script:
    - pip install twine~=1.13.0
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
    - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    refs:
      - tags
    variables:
      - $PYPI_USERNAME
      - $PYPI_PASSWORD
trigger:
  stage: trigger
  image: alpine:3.9
  before_script:
    - apk add --no-cache curl git
  script:
    # XXX: Workaround for GitLab missing latest tag pipeline triggering feature
    - |
      SATNOGS_DB_LATEST="${SATNOGS_DB_GIT_URL:+$(git ls-remote -q --tags --refs --exit-code --sort="v:refname" "$SATNOGS_DB_GIT_URL" | awk 'BEGIN { FS="/" } END { print $3 }')}"
      PIPELINE_TRIGGERS=$(echo "$PIPELINE_TRIGGERS" | sed 's/{{SATNOGS_DB_LATEST}}/'"$SATNOGS_DB_LATEST"'/g')
    - for trigger in $PIPELINE_TRIGGERS; do curl -X POST "$trigger"; done
  only:
    refs:
      - tags
    variables:
      - $PIPELINE_TRIGGERS
