#!/usr/bin/env python3
import json
import argparse
import decode_frame

from datetime import datetime

from satnogsdecoders import decoder


def decode_frame(decoder_name, raw_frame):
    decoder_class = getattr(decoder,
                            decoder_name.capitalize())
    frame = decoder_class.from_bytes(raw_frame)

    fields = decoder.get_fields(frame, empty=False)
    return fields


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Decode a raw frame with the selected decoder'
                                                 '(generated by Kaitai) and print its json representation.')
    parser.add_argument('decoder_name', type=str, help='name of the decoder (e.g. siriussat)')
    parser.add_argument('raw_frame_file',
                        type=str,
                        help='Path to the file containing the raw frame')
    args = parser.parse_args()

    # Load the raw frame
    with open(args.raw_frame_file, 'rb') as f:
        raw_frame = f.read()

    fields = decode_frame(args.decoder_name, raw_frame)
    print(json.dumps(fields, indent=4, sort_keys=False))
